name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: 'AzureCloud'
      
      - name: Set Up Node.js for Azure Deployment
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | 

      - name: Deploy to Azure using FTP
        run: |
          az webapp deployment user set --user-name ${{megaclaim__test\$megaclaim__test }} --password ${{ r51i2GeuirQzjAg4lkKXX2n8wHBNHmud2qm6GAu1LoFR31hAnmdNM0x6eArg}}
          lftp -c "set ftp:ssl-allow no; open -u ${{ secrets.AZURE_FTP_USERNAME }},${{ secrets.AZURE_FTP_PASSWORD }} ftps://waws-prod-dxb-007.ftp.azurewebsites.windows.net/site/wwwroot
