name: demotest

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: '<Your-App-Name>'  # Replace with your Azure Web App name
          slot-name: 'production'  # If deploying to a specific slot, replace with the slot name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'dist/your-angular-app'  # Adjust to your Angular app's build output directory

  cleanup:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Clean up
        run: rm -rf ${{ github.workspace }}/dist
