name: demotest

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v20

      - name: Set Up Node.js
        uses: actions/setup-node@v20
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v20

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v20
        with:
          app-name: '<demotest>'  
          slot-name: 'production'  #
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'dist/your-angular-app'  #

