name: deploy-to-azure.yml

on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies and build Angular app
        run: |
          npm install
          npm run build -- --prod

      - name: Deploy to Azure Web App
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: '/site/wwwroot'
          local-dir: 'dist/your-angular-app'  # Adjust this to your Angular app's build output directory
          exclude: ''
          args: --verbose --disable-utf8
