name: CI/CD Pipeline for Angular App

on:

  push:

    branches: main

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest 

    steps:

      - uses: actions/checkout@v3

      - name: Use Node.js 18.18.2

        uses: actions/setup-node@v3

        with:

          node-version: 18.18.2  

      - name: Install dependencies

        run: npm install 
      - name: Install cli

        run: npm install --save-dev @angular/cli

      - name: Build the Angular app

        run: npx ng build

      - name: Upload to Azure WebApp using FTP

        uses: ercindedeoglu/ftp-transfer-action@v2

        with:

          host: ${{demotest.ftp.azurewebsites.windows.net}}

          user: ${{megaclaim__test}}

        password: ${{r51i2GeuirQzjAg4lkKXX2n8wHBNHmud2qm6GAu1LoFR31hAnmdNM0x6eArg}}

        forceSSL: true

        source: './dist/barcelona-ng/'

    destination: '/site/wwwroot/



      
